#!/usr/bin/env python
import sys
from PyQt4.QtGui import *


def main():
    app = QApplication(sys.argv)

    widget = QWidget()
    widget.show()

    app.exec_()

if __name__ == '__main__':
    sys.exit(main())
